### PR TITLE
[DNM] Process inventory files

### PR DESCRIPTION
**Pull request by gtema**
read/write inventory files for later machine updates

### CODE REVIEW

**Comment by gtema** [comment]
@kucerakk, @lego963 this is how our inventory files will look like when we merge https://github.com/opentelekomcloud-infra/system-config/pull/282

**Review by kucerakk — APPROVED** [review]
A bit sad, that we will miss the comments from the inventory, but I think it is still readable.

**Comment by gtema** [comment]
well, we have actually an alternative: individual inventories reuse group_vars/all.yaml where we define something like:
- grafana_image_stable
- grafana_image_latest
- apimon_image_stable (build for prod)
- apimon_image_latest (dev build for stg)
- etc
This way we can only manipulate single file leaving free form in all others

**Comment by lego963** [comment]
do you want to store all images in one file?

**Review by lego963 — APPROVED** [review]

**Comment by gtema** [comment]
> Do you want to store all images in one file? If we use this approach, we won't ruin yaml configs :)
> 
> UPD: I've found a key in `yaml.safe_dump()` which won't sort keys (because it sorts now).

Well, not the sorting is the problem, but the fact that we loose the structure which makes it easier to read inventory for the human. However:
- inventory is not really targeting human. We define inventory to be used by machine. However we maintain it and need to update it periodically
- have a single file defining all image versions and other files referring to the value in this file makes it much easier - we still have a place which we can easily update by script, and other places also remain human readable

**Comment by lego963** [comment]
> > Do you want to store all images in one file? If we use this approach, we won't ruin yaml configs :)
> > UPD: I've found a key in `yaml.safe_dump()` which won't sort keys (because it sorts now).
> 
> Well, not the sorting is the problem, but the fact that we loose the structure which makes it easier to read inventory for the human. However:
> 
> * inventory is not really targeting human. We define inventory to be used by machine. However we maintain it and need to update it periodically
> * have a single file defining all image versions and other files referring to the value in this file makes it much easier - we still have a place which we can easily update by script, and other places also remain human readable

Let's make one file to rule them all :D

**Pull request closed without merging**
